language: ruby

rvm:
  - 1.9.3
  - 2.3.1

addons:
  chrome: stable

before_install:
  - gem install bundler

before_script:
  - chmod 777 ./config/before-travis.sh
  - ./config/before-travis.sh

script:
  - export DISPLAY=:99.0
  - export LC_CTYPE=en_US.UTF-8
  - bundle exec rake

branches:
  only:
    - master
    - 6-5-0

